config/routes.rb
  get "falla_sesion" => "principal#falla_sesion", :as => "falla_sesion"
  get "deudas" => "principal#deudas", :as => "deudas"
  get "cuenta_inactiva" => "principal#cuenta_inactiva", :as => "cuenta_inactiva"
  get "mision" => "principal#mision", :as => "mision"
  get "vision" => "principal#vision", :as => "vision"
  get "directivos" => "principal#directivos", :as => "directivos"
  get "resena" => "principal#resena", :as => "resena"
  get "etica" => "principal#etica", :as => "etica"
  get "ley" => "principal#ley", :as => "ley"
  get "reglamento" => "principal#reglamento", :as => "reglamento"
  get "novedades" => "principal#novedades", :as => "novedades"
  get "propiedades" => "principal#propiedades", :as => "propiedades"
  get "contacto" => "principal#contacto", :as => "contacto"
  get "denegado" => "principal#denegado", :as => "denegado"

  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  
  get "lista" => "personas#lista", :as => "lista"
  get "new_person" => "personas#new", :as => "new_person"
  get "index_person" => "personas#index", :as => "index_person"
  get 'personas/update_demandante', :as => 'update_demandante'
  post "reporte_demandante" => "personas#reporte_demandante", :as => "reporte_demandante"

  get "index_usuarios" => "users#index", :as => "index_usuarios"
  get "sing_up" => "users#new", :as => "sing_up"
  get "activar_cuentas" => "users#activar_cuentas", :as => "activar_cuentas"
  get "edit_usuarios" => "users#edit", :as => "edit_usuarios"
  get 'users/usu_username_check', :as => 'usu_username_check'
  get 'users/usu_matr_prof_check', :as => 'usu_matr_prof_check'
  get 'users/pers_cedula_check', :as => 'pers_cedula_check'
  get 'users/pers_email_check', :as => 'pers_email_check'
  get 'users/edit_password', :as => 'edit_password'
  post "destroy_usuario" => "users#destroy", :as => "destroy_usuario"
  post "reporte_amount" => "users#reporte_amount", :as => "reporte_amount"
  
  get "index_role" => "roles#index", :as => "index_role"
  get "new_role" => "roles#new", :as => "new_role"
  get "edit_role" => "roles#edit", :as => "edit_role"
  get "show_role" => "roles#show", :as => "show_role"
  post "destroy_role" => "roles#destroy", :as => "destroy_role"

  get "index_property" => "properties#index", :as => "index_property"
  get "new_property" => "properties#new", :as => "new_property"
  get "edit_property" => "properties#edit", :as => "edit_property"
  get "show_property" => "properties#show", :as => "show_property"
  post "destroy_property" => "properties#destroy", :as => "destroy_property"

  get "index_operation" => "operations#index", :as => "index_operation"
  get "new_operation" => "operations#new", :as => "new_operation"
  get "edit_operation" => "operations#edit", :as => "edit_operation"
  get "show_operation" => "operations#show", :as => "show_operation"
  post "destroy_operation" => "operations#destroy", :as => "destroy_operation"

  get "index_channel" => "channels#index", :as => "index_channel"
  get "new_channel" => "channels#new", :as => "new_channel"
  get "edit_channel" => "channels#edit", :as => "edit_channel"
  get "show_channel" => "channels#show", :as => "show_channel"
  post "destroy_channel" => "channels#destroy", :as => "destroy_channel"

  get "index_province" => "provinces#index", :as => "index_province"
  get "new_province" => "provinces#new", :as => "new_province"
  get "edit_province" => "provinces#edit", :as => "edit_province"
  get "show_province" => "provinces#show", :as => "show_province"
  post "destroy_province" => "provinces#destroy", :as => "destroy_province"

  get "index_canton" => "cantons#index", :as => "index_canton"
  get "new_canton" => "cantons#new", :as => "new_canton"
  get "edit_canton" => "cantons#edit", :as => "edit_canton"
  get "show_canton" => "cantons#show", :as => "show_canton"
  post "destroy_canton" => "cantons#destroy", :as => "destroy_canton"

  get "index_parish" => "parishes#index", :as => "index_parish"
  get "new_parish" => "parishes#new", :as => "new_parish"
  get "edit_parish" => "parishes#edit", :as => "edit_parish"
  get "show_parish" => "parishes#show", :as => "show_parish"
  post "destroy_parish" => "parishes#destroy", :as => "destroy_parish"

  get "index_piece" => "pieces#index", :as => "index_piece"
  get "new_piece" => "pieces#new", :as => "new_piece"
  get "edit_piece" => "pieces#edit", :as => "edit_piece"
  get "show_piece" => "pieces#show", :as => "show_piece"
  post "destroy_piece" => "pieces#destroy", :as => "destroy_piece"

  get "index_price" => "prices#index", :as => "index_price"
  get "new_price" => "prices#new", :as => "new_price"
  get "edit_price" => "prices#edit", :as => "edit_price"
  get "show_price" => "prices#show", :as => "show_price"
  post "destroy_price" => "prices#destroy", :as => "destroy_price"

  get "index_parameter" => "parameters#index", :as => "index_parameter"
  get "new_parameter" => "parameters#new", :as => "new_parameter"
  get "edit_parameter" => "parameters#edit", :as => "edit_parameter"
  get "show_parameter" => "parameters#show", :as => "show_parameter"
  post "destroy_parameter" => "parameters#destroy", :as => "destroy_parameter"

  get "index_description" => "descriptions#index", :as => "index_description"
  get "new_description" => "descriptions#new", :as => "new_description"
  get "edit_description" => "descriptions#edit", :as => "edit_description"
  get "show_description" => "descriptions#show", :as => "show_description"
  post "destroy_description" => "descriptions#destroy", :as => "destroy_description"

  get "index_rebate" => "rebates#index", :as => "index_rebate"
  get "new_rebate" => "rebates#new", :as => "new_rebate"
  get "edit_rebate" => "rebates#edit", :as => "edit_rebate"
  get "show_rebate" => "rebates#show", :as => "show_rebate"
  post "destroy_rebate" => "rebates#destroy", :as => "destroy_rebate"

  get "index_state" => "states#index", :as => "index_state"
  get "new_state" => "states#new", :as => "new_state"
  get "edit_state" => "states#edit", :as => "edit_state"
  get "show_state" => "states#show", :as => "show_state"
  post "destroy_state" => "states#destroy", :as => "destroy_state"

  get "index_construction" => "constructions#index", :as => "index_construction"
  get "new_construction" => "constructions#new", :as => "new_construction"
  get "edit_construction" => "constructions#edit", :as => "edit_construction"
  get "show_construction" => "constructions#show", :as => "show_construction"
  get "search_construction" => "constructions#search", :as => "search_construction"
  get "close_construction" => "constructions#close", :as => "close_construction"
  get "coordenadas_construction" => "constructions#coordenadas", :as => "coordenadas_construction"
  get 'constructions/update_cantons', :as => 'update_cantons'
  get 'constructions/update_parishes', :as => 'update_parishes'
  get 'constructions/update_propietario', :as => 'update_propietario'
  get 'constructions/pers_email_check', :as => 'constructions_pers_email_check'
  get 'constructions/demand_email_check', :as => 'constructions_demand_email_check'
  get "todos_constructions" => "constructions#todos", :as => "todos_constructions"
  post "destroy_construction" => "constructions#destroy", :as => "destroy_construction"

  get '/chats/samplea'

  get "new_avaluo" => "avaluos#new", :as => "new_avaluo"
  get "update_avaluo" => "avaluos#update_avaluo", :as => "update_avaluo"

  get 'avaluos/update_description_val', :as => 'update_description_val'
  get 'avaluos/update_state_val', :as => 'update_state_val'
  get 'avaluos/update_tabla_total', :as => 'update_tabla_total'
  post "aval_update" => "avaluos#update", :as => "aval_update"

  get "index_images" => "images#index", :as => "index_images"
  post "destroy_image" => "images#destroy", :as => "destroy_image"

  get "index_meeting" => "meetings#index", :as => "index_meeting"
  get "new_meeting" => "meetings#new", :as => "new_meeting"
  get "edit_meeting" => "meetings#edit", :as => "edit_meeting"
  post "destroy_meeting" => "meetings#destroy", :as => "destroy_meeting"

  get "index_diary" => "diaries#index", :as => "index_diary"
  get "new_diary" => "diaries#new", :as => "new_diary"
  get "edit_diary" => "diaries#edit", :as => "edit_diary"
  post "destroy_diary" => "diaries#destroy", :as => "destroy_diary"

  get "index_honorary" => "honoraries#index", :as => "index_honorary"
  get "new_honorary" => "honoraries#new", :as => "new_honorary"
  get "edit_honorary" => "honoraries#edit", :as => "edit_honorary"
  get "show_honorary" => "honoraries#show", :as => "show_honorary"
  get "todos_honorary" => "honoraries#todos", :as => "todos_honorary"
  post "destroy_honorary" => "honoraries#destroy", :as => "destroy_honorary"
  post "reporte_honorary" => "honoraries#reporte_honorary", :as => "reporte_honorary"

  get "index_amount" => "amounts#index", :as => "index_amount"
  get "new_amount" => "amounts#new", :as => "new_amount"
  get "edit_amount" => "amounts#edit", :as => "edit_amount"
  get "show_amount" => "amounts#show", :as => "show_amount"
  post "destroy_amount" => "amounts#destroy", :as => "destroy_amount"

  get "list_detalle" => "personas_roles_usuarios#nombres", :as => "list_detalle"

    
  resources :users
  resources :sessions
  resources :personas
  resources :roles
  resources :principal
  resources :properties
  resources :operations
  resources :channels
  resources :provinces
  resources :personas_roles_usuarios
  resources :cantons
  resources :parishes
  resources :pieces
  resources :prices
  resources :parameters
  resources :descriptions
  resources :parameters_descriptions
  resources :rebates
  resources :states
  resources :constructions
  resources :avaluos
  resources :constructions_prices
  resources :areas
  resources :images
  resources :meetings
  resources :diaries
  resources :honoraries
  resources :amounts
  resources :password_resets
  
  
match ':controller(/:action(/:id))(.:format)'

app/models/parish.rb
class Parish < ActiveRecord::Base
  attr_accessible :parr_nombre, :canton_id
  belongs_to :canton
  has_many :constructions#, :dependent => :destroy
  validate :blanco
  def blanco
    self.parr_nombre = self.parr_nombre.gsub(/\s+/, " ").strip
  end
end

app/controllers/parishes_controller.rb
class ParishesController < ApplicationController
  def index
    rol_administrador = Role.find_by_rol_nombre("Administrador")
    administrador = User.joins(:roles).where(:personas_roles_users=>{:role_id=>rol_administrador.id, :user_id=>current_user})
    if current_user and administrador.exists?
      @id = params[:canton_id]
      @canton = Canton.find(@id)
      @province = Province.find(@canton.province_id)
      @parroquias = Parish.joins(:canton).where(:canton_id=>@id)
      @parroquia = Parish.new
      respond_to do |format|
        format.js
        format.html
      end
    else
      redirect_to denegado_path
    end
    rescue ActiveRecord::RecordNotFound
      redirect_to denegado_path
    return
  end

  def new
    @parroquia = Parish.new
    @id = params[:canton_id]
  end

  def create
    @parroquia = Parish.new(params[:parish])
    respond_to do |format|
      @parroquia.parr_nombre = @parroquia.parr_nombre.gsub(/\s+/, " ").strip
      if @parroquia.parr_nombre == ""
        @bandera = "blank"
        format.js { render "create.js"}
      else
        @parroquias = Parish.where(:canton_id=>@parroquia.canton_id)
        if @parroquias.find_by_parr_nombre(@parroquia.parr_nombre)
          @bandera = "exist"
          format.js { render "create.js"}
        else
          mayuscula = (@parroquia.parr_nombre).upcase
          @parroquias.each do |p|
            if (p.parr_nombre).upcase == mayuscula
              @bandera = "exist"
            end
          end
          if @bandera == "exist"
            format.js { render "create.js"}
          else
            if @parroquia.save
              format.html { redirect_to index_parish_path(:canton_id => @parroquia.canton_id), :notice => "Registrado"}
            end
          end
        end
      end
    end
  end

  def show
    @parroquia = Parish.find(params[:id])
  end

  def eliminar
    @parroquia = Parish.find(params[:id])
    respond_to do |format|
      if Construction.find_by_parish_id(@parroquia.id)
        format.js { render "no_eliminar.js"}
      else
        format.js { render "eliminar.js"}
      end
    end
    rescue ActiveRecord::RecordNotFound
      redirect_to denegado_path
    return
  end

  def destroy
    @parroquia = Parish.find(params[:id])
    @parroquia.destroy
    redirect_to index_parish_path(:canton_id => @parroquia.canton_id)
  end

  def edit
   @parroquia = Parish.find(params[:id])
   respond_to do |format|
     format.js { render "edit.js"}
   end
   rescue ActiveRecord::RecordNotFound
      redirect_to denegado_path
    return
  end

  def update
    @parroquia = Parish.new(params[:parish])
    respond_to do |format|
      @parroquia.parr_nombre = @parroquia.parr_nombre.gsub(/\s+/, " ").strip
      if @parroquia.parr_nombre == ""
        @bandera = "blank"
        format.js { render "update.js"}
      else
        aux_parroquia = Parish.find(params[:id])
        @parroquias = Parish.where(:canton_id=>params[:canton_id])
        if @parroquias.find_by_parr_nombre(@parroquia.parr_nombre) and (@parroquia.parr_nombre != aux_parroquia.parr_nombre)
          @bandera = "exist"
          format.js { render "update.js"}
        else
          mayuscula = (@parroquia.parr_nombre).upcase
          @parroquias.each do |p|
            if ((p.parr_nombre).upcase == mayuscula) and (p.parr_nombre).upcase != (aux_parroquia.parr_nombre).upcase
              @bandera = "exist"
            end
          end
          if @bandera == "exist"
            format.js { render "update.js"}
          else
            @parroquia = Parish.find(params[:id])
            if @parroquia.update_attributes(params[:parish])
              format.html { redirect_to index_parish_path(:canton_id => @parroquia.canton_id), :notice => "Registrado"}
            end
          end
        end
      end
    end
  end
end

app/helpers/parishes_helper.rb
module ParishesHelper
end

app/views/parishes/_edit.html.erb
<script>
  $("#advertencia_edit").hide();
</script>
<div id="form_edit_parish">
  <%= form_for @parroquia, :remote=>true do |p|%>
    <div id="formulario">
      <table>
        <tr>
          <td><%= label_tag nil, "Nombre de Parroquia:" %></td>
          <td><%= p.text_field :parr_nombre, :id=>"parishes_edit_parr_nombre", :autofocus => true %></td>
        </tr>
        <%= hidden_field_tag :canton_id, @parroquia.canton_id %>
        <tr>
          <td colspan="2" class="centrar_obj"><%= label_tag nil, "", :id=>"advertencia_edit", :class=>"mensaje" %></td>
        </tr>
        <!--<tr>
          <td colspan="2" class="boton"><%#= p.submit "Guardar"%></td>
        </tr>-->
      </table>
    </div>
  <%end%>
</div>

app/views/parishes/_eliminar.html.erb
<div id="formulario">
  <div id="form_eliminar_parish">
    <%= form_tag destroy_parish_path do%>
      <%= label_tag nil, "Esta seguro que desea eliminar '#{@parroquia.parr_nombre}'"%>
      <%= hidden_field_tag :id, @parroquia.id  %>
    <%end%>
  </div>
</div>

app/views/parishes/_no_eliminar.html.erb
<div id="formulario">
  <%= label_tag nil, "No puede eliminar la Parroquia '#{@parroquia.parr_nombre}' porque tiene datos asociados."%>
</div>

app/views/parishes/_show.html.erb
<div id="formulario">
  <%= label_tag nil, "", :id=>"advertencia_new", :class=>"mensaje"%>
</div>

app/views/parishes/create.js.erb
$('#parish_new').html('<%= escape_javascript(render :partial =>'parishes/show')%>');
if ('<%= @bandera%>' == "blank")
{ $('#advertencia_new').html('<%= escape_javascript('ATENCION: Faltan datos por ingresar')%>');}
else
{ if ('<%= @bandera%>' == "exist")
  { $('#advertencia_new').html('<%= escape_javascript("#{@parroquia.parr_nombre}"+' ya existe, por favor ingrese otro nombre')%>');}
}
document.getElementById("advertencia_new").style.color="#F50E0E";
$('#parish_new').dialog({
  resizable: false,
  height: 'auto',
  width: 'auto',
  title: "Nuevo",
  modal: true,
  buttons: {
                "OK" : function()
                {
                    $("#parish_new").dialog("close");
                    document.getElementById("parishes_index_parr_nombre").focus();
                    $('#parishes_index_parr_nombre').val("");
                }
            }
});

app/views/parishes/edit.js.erb
$('#parish_edit').html('<%= escape_javascript(render :partial =>'parishes/edit')%>');
$('#parish_edit').dialog({
  resizable: false,
  height: 'auto',
  width: 'auto',
  title: "Editar",
  modal: true,
  buttons: {
                "Guardar": function()
                {
                    $("#form_edit_parish form").submit();
                },
                "Cancelar" : function()
                {
                    $("#parish_edit").dialog("close");
                }
            }
});

app/views/parishes/eliminar.js.erb
$('#parish_delete').html('<%= escape_javascript(render :partial =>'parishes/eliminar')%>');
$('#parish_delete').dialog({
  resizable: false,
  height: 'auto',
  width: 'auto',
  title: "Eliminar",
  modal: true,
  buttons: {
                "Aceptar": function()
                {
                    $("#form_eliminar_parish form").submit();
                },
                "Cancelar" : function()
                {
                    $("#parish_delete").dialog("close");
                }
            }
});

app/views/parishes/index.html.erb
<script language="JavaScript" type="text/javascript" src="/javascripts/jquery-ui.js"></script>
<link rel="stylesheet" href="/stylesheets/jquery-ui.css"></link>
<%= stylesheet_link_tag "tablas.css", :media => "screen" %>
<%= label_tag nil, (link_to ">> Provincias ", index_province_path), :class=>"negrita" %><%= label_tag nil, (">> " + @province.prov_nombre), :class=>"negrita" %><%= label_tag nil, (link_to ">> Cantones ", index_canton_path(:province_id => @canton.province_id)), :class=>"negrita" %><%= label_tag nil, (">> " + @canton.cant_nombre), :class=>"negrita" %>
<div id="tabla">
  <table class="bordered">
    <th><div class="titulos"><p>Parroquia</p></div></th>
    <th><div class="titulos"><p>Acciones</p></div></th>
    <% @parroquias.each do |p| %>
      <tr>
        <td><%= label_tag nil, p.parr_nombre %></td>
        <td><%= label_tag nil, (link_to (image_tag "contenido/edit16.png"), {:action => "edit", :id => p.id}, :remote=>true) %><%= label_tag nil, (link_to (image_tag "contenido/delete16.png"), {:action=>"eliminar", :id=>p.id}, :remote=>true) %></td>
      </tr>
    <% end %>
    <%= form_for @parroquia, :remote=>true do |p|%>
      <tr>
        <td><%= p.text_field :parr_nombre, :id=>"parishes_index_parr_nombre", :autofocus => true %></td>
        <%= p.hidden_field :canton_id, value: @id %>
        <td><%= label_tag nil, image_submit_tag("contenido/add2-16.png")%></td>
      </tr>
    <%end%>
  </table>
</div>
<div id="parish_new">

</div>
<div id="parish_edit">

</div>
<div id="parish_delete">

</div>
<div id="parish_no_delete">

</div>
<%#= link_to 'Agregar nueva parroquia', new_parish_path(:canton_id => @id) %>

app/views/parishes/index.js.erb
window.location = '<%= index_parish_path(:canton_id => @id) %>';

app/views/parishes/new.html.erb
<%= form_for @parroquia do |p|%>
  <p>
    <%= p.label :"Nombre de Parroquia" %>
    <%= p.text_field :parr_nombre %>
    <%= p.hidden_field :canton_id, value: @id %>
  </p>
  <p>
    <%= p.submit "Guardar"%>
  </p>
<%end%>

app/views/parishes/no_eliminar.js.erb
$('#parish_no_delete').html('<%= escape_javascript(render :partial =>'parishes/no_eliminar')%>');
$('#parish_no_delete').dialog({
  resizable: false,
  height: 'auto',
  width: 'auto',
  title: "Eliminar",
  modal: true,
  buttons: {
                "Aceptar": function()
                {
                    $("#parish_no_delete").dialog("close");
                }
            }
});

app/views/parishes/update.js.erb
if ('<%= @bandera%>' == "blank")
{ $('#advertencia_edit').html('<%= escape_javascript('ATENCION: Faltan datos por ingresar')%>');}
else
{ if ('<%= @bandera%>' == "exist")
  { $('#advertencia_edit').html('<%= escape_javascript('El nombre ya existe, por favor ingrese uno diferente')%>');}
}
document.getElementById("advertencia_edit").style.color="#F50E0E";
$('#advertencia_edit').show();
setTimeout(function(){$('#advertencia_edit').hide()},6000);
document.getElementById("parishes_edit_parr_nombre").focus();
$("#parishes_edit_parr_nombre").val("");