config/routes.rb
  get "falla_sesion" => "principal#falla_sesion", :as => "falla_sesion"
  get "deudas" => "principal#deudas", :as => "deudas"
  get "cuenta_inactiva" => "principal#cuenta_inactiva", :as => "cuenta_inactiva"
  get "mision" => "principal#mision", :as => "mision"
  get "vision" => "principal#vision", :as => "vision"
  get "directivos" => "principal#directivos", :as => "directivos"
  get "resena" => "principal#resena", :as => "resena"
  get "etica" => "principal#etica", :as => "etica"
  get "ley" => "principal#ley", :as => "ley"
  get "reglamento" => "principal#reglamento", :as => "reglamento"
  get "novedades" => "principal#novedades", :as => "novedades"
  get "propiedades" => "principal#propiedades", :as => "propiedades"
  get "contacto" => "principal#contacto", :as => "contacto"
  get "denegado" => "principal#denegado", :as => "denegado"

  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  
  get "lista" => "personas#lista", :as => "lista"
  get "new_person" => "personas#new", :as => "new_person"
  get "index_person" => "personas#index", :as => "index_person"
  get 'personas/update_demandante', :as => 'update_demandante'
  post "reporte_demandante" => "personas#reporte_demandante", :as => "reporte_demandante"

  get "index_usuarios" => "users#index", :as => "index_usuarios"
  get "sing_up" => "users#new", :as => "sing_up"
  get "activar_cuentas" => "users#activar_cuentas", :as => "activar_cuentas"
  get "edit_usuarios" => "users#edit", :as => "edit_usuarios"
  get 'users/usu_username_check', :as => 'usu_username_check'
  get 'users/usu_matr_prof_check', :as => 'usu_matr_prof_check'
  get 'users/pers_cedula_check', :as => 'pers_cedula_check'
  get 'users/pers_email_check', :as => 'pers_email_check'
  get 'users/edit_password', :as => 'edit_password'
  post "destroy_usuario" => "users#destroy", :as => "destroy_usuario"
  post "reporte_amount" => "users#reporte_amount", :as => "reporte_amount"
  
  get "index_role" => "roles#index", :as => "index_role"
  get "new_role" => "roles#new", :as => "new_role"
  get "edit_role" => "roles#edit", :as => "edit_role"
  get "show_role" => "roles#show", :as => "show_role"
  post "destroy_role" => "roles#destroy", :as => "destroy_role"

  get "index_property" => "properties#index", :as => "index_property"
  get "new_property" => "properties#new", :as => "new_property"
  get "edit_property" => "properties#edit", :as => "edit_property"
  get "show_property" => "properties#show", :as => "show_property"
  post "destroy_property" => "properties#destroy", :as => "destroy_property"

  get "index_operation" => "operations#index", :as => "index_operation"
  get "new_operation" => "operations#new", :as => "new_operation"
  get "edit_operation" => "operations#edit", :as => "edit_operation"
  get "show_operation" => "operations#show", :as => "show_operation"
  post "destroy_operation" => "operations#destroy", :as => "destroy_operation"

  get "index_channel" => "channels#index", :as => "index_channel"
  get "new_channel" => "channels#new", :as => "new_channel"
  get "edit_channel" => "channels#edit", :as => "edit_channel"
  get "show_channel" => "channels#show", :as => "show_channel"
  post "destroy_channel" => "channels#destroy", :as => "destroy_channel"

  get "index_province" => "provinces#index", :as => "index_province"
  get "new_province" => "provinces#new", :as => "new_province"
  get "edit_province" => "provinces#edit", :as => "edit_province"
  get "show_province" => "provinces#show", :as => "show_province"
  post "destroy_province" => "provinces#destroy", :as => "destroy_province"

  get "index_canton" => "cantons#index", :as => "index_canton"
  get "new_canton" => "cantons#new", :as => "new_canton"
  get "edit_canton" => "cantons#edit", :as => "edit_canton"
  get "show_canton" => "cantons#show", :as => "show_canton"
  post "destroy_canton" => "cantons#destroy", :as => "destroy_canton"

  get "index_parish" => "parishes#index", :as => "index_parish"
  get "new_parish" => "parishes#new", :as => "new_parish"
  get "edit_parish" => "parishes#edit", :as => "edit_parish"
  get "show_parish" => "parishes#show", :as => "show_parish"
  post "destroy_parish" => "parishes#destroy", :as => "destroy_parish"

  get "index_piece" => "pieces#index", :as => "index_piece"
  get "new_piece" => "pieces#new", :as => "new_piece"
  get "edit_piece" => "pieces#edit", :as => "edit_piece"
  get "show_piece" => "pieces#show", :as => "show_piece"
  post "destroy_piece" => "pieces#destroy", :as => "destroy_piece"

  get "index_price" => "prices#index", :as => "index_price"
  get "new_price" => "prices#new", :as => "new_price"
  get "edit_price" => "prices#edit", :as => "edit_price"
  get "show_price" => "prices#show", :as => "show_price"
  post "destroy_price" => "prices#destroy", :as => "destroy_price"

  get "index_parameter" => "parameters#index", :as => "index_parameter"
  get "new_parameter" => "parameters#new", :as => "new_parameter"
  get "edit_parameter" => "parameters#edit", :as => "edit_parameter"
  get "show_parameter" => "parameters#show", :as => "show_parameter"
  post "destroy_parameter" => "parameters#destroy", :as => "destroy_parameter"

  get "index_description" => "descriptions#index", :as => "index_description"
  get "new_description" => "descriptions#new", :as => "new_description"
  get "edit_description" => "descriptions#edit", :as => "edit_description"
  get "show_description" => "descriptions#show", :as => "show_description"
  post "destroy_description" => "descriptions#destroy", :as => "destroy_description"

  get "index_rebate" => "rebates#index", :as => "index_rebate"
  get "new_rebate" => "rebates#new", :as => "new_rebate"
  get "edit_rebate" => "rebates#edit", :as => "edit_rebate"
  get "show_rebate" => "rebates#show", :as => "show_rebate"
  post "destroy_rebate" => "rebates#destroy", :as => "destroy_rebate"

  get "index_state" => "states#index", :as => "index_state"
  get "new_state" => "states#new", :as => "new_state"
  get "edit_state" => "states#edit", :as => "edit_state"
  get "show_state" => "states#show", :as => "show_state"
  post "destroy_state" => "states#destroy", :as => "destroy_state"

  get "index_construction" => "constructions#index", :as => "index_construction"
  get "new_construction" => "constructions#new", :as => "new_construction"
  get "edit_construction" => "constructions#edit", :as => "edit_construction"
  get "show_construction" => "constructions#show", :as => "show_construction"
  get "search_construction" => "constructions#search", :as => "search_construction"
  get "close_construction" => "constructions#close", :as => "close_construction"
  get "coordenadas_construction" => "constructions#coordenadas", :as => "coordenadas_construction"
  get 'constructions/update_cantons', :as => 'update_cantons'
  get 'constructions/update_parishes', :as => 'update_parishes'
  get 'constructions/update_propietario', :as => 'update_propietario'
  get 'constructions/pers_email_check', :as => 'constructions_pers_email_check'
  get 'constructions/demand_email_check', :as => 'constructions_demand_email_check'
  get "todos_constructions" => "constructions#todos", :as => "todos_constructions"
  post "destroy_construction" => "constructions#destroy", :as => "destroy_construction"

  get '/chats/samplea'

  get "new_avaluo" => "avaluos#new", :as => "new_avaluo"
  get "update_avaluo" => "avaluos#update_avaluo", :as => "update_avaluo"

  get 'avaluos/update_description_val', :as => 'update_description_val'
  get 'avaluos/update_state_val', :as => 'update_state_val'
  get 'avaluos/update_tabla_total', :as => 'update_tabla_total'
  post "aval_update" => "avaluos#update", :as => "aval_update"

  get "index_images" => "images#index", :as => "index_images"
  post "destroy_image" => "images#destroy", :as => "destroy_image"

  get "index_meeting" => "meetings#index", :as => "index_meeting"
  get "new_meeting" => "meetings#new", :as => "new_meeting"
  get "edit_meeting" => "meetings#edit", :as => "edit_meeting"
  post "destroy_meeting" => "meetings#destroy", :as => "destroy_meeting"

  get "index_diary" => "diaries#index", :as => "index_diary"
  get "new_diary" => "diaries#new", :as => "new_diary"
  get "edit_diary" => "diaries#edit", :as => "edit_diary"
  post "destroy_diary" => "diaries#destroy", :as => "destroy_diary"

  get "index_honorary" => "honoraries#index", :as => "index_honorary"
  get "new_honorary" => "honoraries#new", :as => "new_honorary"
  get "edit_honorary" => "honoraries#edit", :as => "edit_honorary"
  get "show_honorary" => "honoraries#show", :as => "show_honorary"
  get "todos_honorary" => "honoraries#todos", :as => "todos_honorary"
  post "destroy_honorary" => "honoraries#destroy", :as => "destroy_honorary"
  post "reporte_honorary" => "honoraries#reporte_honorary", :as => "reporte_honorary"

  get "index_amount" => "amounts#index", :as => "index_amount"
  get "new_amount" => "amounts#new", :as => "new_amount"
  get "edit_amount" => "amounts#edit", :as => "edit_amount"
  get "show_amount" => "amounts#show", :as => "show_amount"
  post "destroy_amount" => "amounts#destroy", :as => "destroy_amount"

  get "list_detalle" => "personas_roles_usuarios#nombres", :as => "list_detalle"

    
  resources :users
  resources :sessions
  resources :personas
  resources :roles
  resources :principal
  resources :properties
  resources :operations
  resources :channels
  resources :provinces
  resources :personas_roles_usuarios
  resources :cantons
  resources :parishes
  resources :pieces
  resources :prices
  resources :parameters
  resources :descriptions
  resources :parameters_descriptions
  resources :rebates
  resources :states
  resources :constructions
  resources :avaluos
  resources :constructions_prices
  resources :areas
  resources :images
  resources :meetings
  resources :diaries
  resources :honoraries
  resources :amounts
  resources :password_resets
  
  
match ':controller(/:action(/:id))(.:format)'

app/models/rebate.rb
class Rebate < ActiveRecord::Base
  attr_accessible :met_nombre, :met_nivel
  has_many :states, :dependent => :destroy

  validate :blanco
  def blanco
    self.met_nombre = self.met_nombre.gsub(/\s+/, " ").strip
#    self.param_val_unit = self.param_val_unit.gsub(/\s+/, " ").strip
  end
end

app/helpers/avaluos_helper.rb
module AvaluosHelper
end

app/views/avaluos/new.html.erb
<%= javascript_include_tag "validaciones_avaluos.js.erb"%>
<script>
  $(document).ready(function() {
    calculoAvaluo("<%= update_description_val_path %>","<%= update_state_val_path %>");    
});
</script>

<%= stylesheet_link_tag "avaluos.css", :media => "screen" %>
<%= form_tag avaluos_path do %>
<div id="form_avaluo">
<fieldset>
  <legend class="avaluo">Tabla de Avaluo</legend>
  <br/>
  <table>
    <tr>
      <td><div class="titulos"><p>Descripcion</p></div></td>
      <td><div class="titulos"><p>Area</p></div></td>
      <td><div class="titulos"><p>Valor Unitario</p></div></td>
      <td><div class="titulos"><p>Total</p></div></td>
    </tr>
    <% @tabla_avaluo.each do |ta| %>
      <tr>
      <td><div class ="etiquetas_left"><%= label_tag nil, ta.aval_descrip, :class => "label_aval_descrip" %></div></td>
        <%= hidden_field_tag "price_ids[]", ta.id %>
        <%#= form_tag @imueble_tabla_avaluo do %>
        <td><%= text_field_tag "det_areas[]", @taa_areas[@cont1], :class => "text_area", :id => "text_area_"+ "#{ta.id}", :style => "width:100px"%></td>
        <td><%= text_field_tag "det_vals_unit[]", @taa_unitarios[@cont1], :class => "text_val_unit", :id => "text_val_unit_"+ "#{ta.id}", :style => "width:100px" %></td>
        <td><%= text_field_tag "det_vals_tot[]", @taa_totales[@cont1], :class => "text_val_tot", :id => "text_val_tot_"+ "#{ta.id}", :style => "width:100px", :readonly => true %></td>
        <%#end%>
      </tr>
      <%@cont1+=1%>
    <%end%>
    <tr>
      
      <td></td>
      <td></td>
      <td><div class ="etiquetas_right"><%= label_tag "Valor de Realizacion"%> </div></td>
      <%#= form_for @inmueble do |i|%>
        <td><%= text_field_tag :inm_val_real, @taa_val_real, {:id => "text_val_real", :style => "width:100px", :readonly => true} %></td>
      <%#end%>

    </tr>
  </table>
</fieldset>
<fieldset>
  <legend class="avaluo">Parametros de Avaluo</legend>
  <br/>
    <table>
    <% @parametro.each do |p| %>
      <tr>
        <td><div class ="etiquetas_left"><%= label_tag nil, p.param_descrip, :class => "label_param_descrip"%></div></td>
        <%= hidden_field_tag "parameter_ids[]", p.id %>
        <td><%= select_tag "description_ids[]", options_from_collection_for_select(p.descriptions.each, "id", "param_val_descrip", @description_actual[@cont2]), :class => "description_select", :id => "description_select_"+ "#{p.id}",:prompt => "Seleccione una descripcion", :style => "width:206px"%></td>
        <td><%= text_field_tag :param_val_unit, @description_actual_valor[@cont2], :id =>"text_param_val_unit_"+ "#{p.id}", :class=>"text_param_val_unit",:style => "width:100px", :disabled => true%></td>
      </tr>
      <%@cont2+=1%>
    <%end%>
    <tr>
      <td></td>
      <td><div class ="etiquetas_right"><%= label_tag "Sumatoria" %></div></td>
      <td><%= text_field_tag :suma_descrip, @sumatoria1, :id=>"text_sum_descrip", :style => "width:100px", :disabled => true %></td>
    </tr>
    <% @met_depr.each do |md| %>
      <tr>
        <td><div class ="etiquetas_left"><%= label_tag :met_nombre, md.met_nombre, :class => "label_met_nombre"%></div></td>
        <td><%= select_tag "state_ids[]", options_from_collection_for_select(md.states.each, "id", "met_val_descrip", @state_actual[@cont3]), :class => "state_select", :id => "state_select_"+ "#{md.id}",:prompt => "Seleccione una opcion", :style => "width:206px"%></td>
        <td><%= text_field_tag :met_val_unit, @state_actual_valor[@cont3], :id =>"text_met_unit_"+ "#{md.id}", :class=>"text_met_unit",:style => "width:100px", :disabled => true%></td>
      </tr>
      <%@cont3+=1%>
    <%end%>
    <tr>
      <td></td>
      <td><div class ="etiquetas_right"><%= label_tag "Sumatoria" %></div></td>
      <td><%= text_field_tag :suma_depr, @sumatoria2, :id=>"text_sum_state", :style => "width:100px", :disabled => true %></td>
    </tr>
    <tr>
      <td></td>
      <td><div class ="etiquetas_right"><%= label_tag "Valor del Mercado" %></div></td>
      <td><%= text_field_tag :val_merc, @taa_val_merc, :id=>"text_val_merc", :style => "width:100px", :readonly => true %></td>
    </tr>


  </table>
</fieldset>

<%= hidden_field_tag :construction_id, @inmueble.id %>
<div class="boton"><%#= @inmueble.id %><%= submit_tag "Guardar"%></div>
</div>
<%end%>
<br/>

app/views/avaluos/update_avaluo.html.erb
<%#@actualizar.each do |a|%>
  <%= @actualizar.construction_id %>
  <%= @actualizar.price_id %>
  <%= @actualizar.det_area %>
  <%= @actualizar.det_val_unit %>
  <%= @actualizar.det_val_tot %>
<%#end%>

app/views/avaluos/update_description_val.js.erb
$('#text_param_val_unit_'+<%= @parameter_id %>).val("<%= @descrip%>");
var selects_descriptions = document.getElementsByClassName("description_select");
var param_val_unit_text = document.getElementsByClassName("text_param_val_unit");
var valor_sum_descrip = 0;
for (var i = 0; i < selects_descriptions.length; i++){
  valor_sum_descrip = valor_sum_descrip + parseFloat(param_val_unit_text[i].value) ;
}
$("#text_sum_descrip").val(valor_sum_descrip);
    var val_real = $("#text_val_real").val();
var sum_descrip = $("#text_sum_descrip").val();
var sum_state = $("#text_sum_state").val();
var sum_val_merc = parseFloat(val_real)+parseFloat(sum_descrip)+parseFloat(sum_state);
$("#text_val_merc").val(parseFloat(sum_val_merc));

app/views/avaluos/update_state_val.js.erb
$('#text_met_unit_'+<%= @rebate_id %>).val("<%= @state%>");
var selects_states = document.getElementsByClassName("state_select");
var met_unit_text = document.getElementsByClassName("text_met_unit");
var valor_sum_state = 0;
for (var i = 0; i < selects_states.length; i++){
  valor_sum_state = valor_sum_state + parseFloat(met_unit_text[i].value) ;
}
$("#text_sum_state").val(valor_sum_state);
    var val_real = $("#text_val_real").val();
var sum_descrip = $("#text_sum_descrip").val();
var sum_state = $("#text_sum_state").val();
var sum_val_merc = parseFloat(val_real)+parseFloat(sum_descrip)+parseFloat(sum_state);
$("#text_val_merc").val(parseFloat(sum_val_merc));

app/views/avaluos/update_tabla_total.js.erb
//$('#text_val_tot_'+<%= @avaluo_id %>).val("<%= @total%>");
//areas[<%= @rec_area%>].value = <%= @val1 %>;
//unitarios[<%= @rec_unitario%>].value = <%= @val2 %>;
//areas = document.getElementsByClassName("text_area");
//unitarios = document.getElementsByClassName("text_val_unit");
//alert($('.'+areas[<%= @rec_area%>].className).val());