config/routes.rb
  get "falla_sesion" => "principal#falla_sesion", :as => "falla_sesion"
  get "deudas" => "principal#deudas", :as => "deudas"
  get "cuenta_inactiva" => "principal#cuenta_inactiva", :as => "cuenta_inactiva"
  get "mision" => "principal#mision", :as => "mision"
  get "vision" => "principal#vision", :as => "vision"
  get "directivos" => "principal#directivos", :as => "directivos"
  get "resena" => "principal#resena", :as => "resena"
  get "etica" => "principal#etica", :as => "etica"
  get "ley" => "principal#ley", :as => "ley"
  get "reglamento" => "principal#reglamento", :as => "reglamento"
  get "novedades" => "principal#novedades", :as => "novedades"
  get "propiedades" => "principal#propiedades", :as => "propiedades"
  get "contacto" => "principal#contacto", :as => "contacto"
  get "denegado" => "principal#denegado", :as => "denegado"

  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  
  get "lista" => "personas#lista", :as => "lista"
  get "new_person" => "personas#new", :as => "new_person"
  get "index_person" => "personas#index", :as => "index_person"
  get 'personas/update_demandante', :as => 'update_demandante'
  post "reporte_demandante" => "personas#reporte_demandante", :as => "reporte_demandante"

  get "index_usuarios" => "users#index", :as => "index_usuarios"
  get "sing_up" => "users#new", :as => "sing_up"
  get "activar_cuentas" => "users#activar_cuentas", :as => "activar_cuentas"
  get "edit_usuarios" => "users#edit", :as => "edit_usuarios"
  get 'users/usu_username_check', :as => 'usu_username_check'
  get 'users/usu_matr_prof_check', :as => 'usu_matr_prof_check'
  get 'users/pers_cedula_check', :as => 'pers_cedula_check'
  get 'users/pers_email_check', :as => 'pers_email_check'
  get 'users/edit_password', :as => 'edit_password'
  post "destroy_usuario" => "users#destroy", :as => "destroy_usuario"
  post "reporte_amount" => "users#reporte_amount", :as => "reporte_amount"
  
  get "index_role" => "roles#index", :as => "index_role"
  get "new_role" => "roles#new", :as => "new_role"
  get "edit_role" => "roles#edit", :as => "edit_role"
  get "show_role" => "roles#show", :as => "show_role"
  post "destroy_role" => "roles#destroy", :as => "destroy_role"

  get "index_property" => "properties#index", :as => "index_property"
  get "new_property" => "properties#new", :as => "new_property"
  get "edit_property" => "properties#edit", :as => "edit_property"
  get "show_property" => "properties#show", :as => "show_property"
  post "destroy_property" => "properties#destroy", :as => "destroy_property"

  get "index_operation" => "operations#index", :as => "index_operation"
  get "new_operation" => "operations#new", :as => "new_operation"
  get "edit_operation" => "operations#edit", :as => "edit_operation"
  get "show_operation" => "operations#show", :as => "show_operation"
  post "destroy_operation" => "operations#destroy", :as => "destroy_operation"

  get "index_channel" => "channels#index", :as => "index_channel"
  get "new_channel" => "channels#new", :as => "new_channel"
  get "edit_channel" => "channels#edit", :as => "edit_channel"
  get "show_channel" => "channels#show", :as => "show_channel"
  post "destroy_channel" => "channels#destroy", :as => "destroy_channel"

  get "index_province" => "provinces#index", :as => "index_province"
  get "new_province" => "provinces#new", :as => "new_province"
  get "edit_province" => "provinces#edit", :as => "edit_province"
  get "show_province" => "provinces#show", :as => "show_province"
  post "destroy_province" => "provinces#destroy", :as => "destroy_province"

  get "index_canton" => "cantons#index", :as => "index_canton"
  get "new_canton" => "cantons#new", :as => "new_canton"
  get "edit_canton" => "cantons#edit", :as => "edit_canton"
  get "show_canton" => "cantons#show", :as => "show_canton"
  post "destroy_canton" => "cantons#destroy", :as => "destroy_canton"

  get "index_parish" => "parishes#index", :as => "index_parish"
  get "new_parish" => "parishes#new", :as => "new_parish"
  get "edit_parish" => "parishes#edit", :as => "edit_parish"
  get "show_parish" => "parishes#show", :as => "show_parish"
  post "destroy_parish" => "parishes#destroy", :as => "destroy_parish"

  get "index_piece" => "pieces#index", :as => "index_piece"
  get "new_piece" => "pieces#new", :as => "new_piece"
  get "edit_piece" => "pieces#edit", :as => "edit_piece"
  get "show_piece" => "pieces#show", :as => "show_piece"
  post "destroy_piece" => "pieces#destroy", :as => "destroy_piece"

  get "index_price" => "prices#index", :as => "index_price"
  get "new_price" => "prices#new", :as => "new_price"
  get "edit_price" => "prices#edit", :as => "edit_price"
  get "show_price" => "prices#show", :as => "show_price"
  post "destroy_price" => "prices#destroy", :as => "destroy_price"

  get "index_parameter" => "parameters#index", :as => "index_parameter"
  get "new_parameter" => "parameters#new", :as => "new_parameter"
  get "edit_parameter" => "parameters#edit", :as => "edit_parameter"
  get "show_parameter" => "parameters#show", :as => "show_parameter"
  post "destroy_parameter" => "parameters#destroy", :as => "destroy_parameter"

  get "index_description" => "descriptions#index", :as => "index_description"
  get "new_description" => "descriptions#new", :as => "new_description"
  get "edit_description" => "descriptions#edit", :as => "edit_description"
  get "show_description" => "descriptions#show", :as => "show_description"
  post "destroy_description" => "descriptions#destroy", :as => "destroy_description"

  get "index_rebate" => "rebates#index", :as => "index_rebate"
  get "new_rebate" => "rebates#new", :as => "new_rebate"
  get "edit_rebate" => "rebates#edit", :as => "edit_rebate"
  get "show_rebate" => "rebates#show", :as => "show_rebate"
  post "destroy_rebate" => "rebates#destroy", :as => "destroy_rebate"

  get "index_state" => "states#index", :as => "index_state"
  get "new_state" => "states#new", :as => "new_state"
  get "edit_state" => "states#edit", :as => "edit_state"
  get "show_state" => "states#show", :as => "show_state"
  post "destroy_state" => "states#destroy", :as => "destroy_state"

  get "index_construction" => "constructions#index", :as => "index_construction"
  get "new_construction" => "constructions#new", :as => "new_construction"
  get "edit_construction" => "constructions#edit", :as => "edit_construction"
  get "show_construction" => "constructions#show", :as => "show_construction"
  get "search_construction" => "constructions#search", :as => "search_construction"
  get "close_construction" => "constructions#close", :as => "close_construction"
  get "coordenadas_construction" => "constructions#coordenadas", :as => "coordenadas_construction"
  get 'constructions/update_cantons', :as => 'update_cantons'
  get 'constructions/update_parishes', :as => 'update_parishes'
  get 'constructions/update_propietario', :as => 'update_propietario'
  get 'constructions/pers_email_check', :as => 'constructions_pers_email_check'
  get 'constructions/demand_email_check', :as => 'constructions_demand_email_check'
  get "todos_constructions" => "constructions#todos", :as => "todos_constructions"
  post "destroy_construction" => "constructions#destroy", :as => "destroy_construction"

  get '/chats/samplea'

  get "new_avaluo" => "avaluos#new", :as => "new_avaluo"
  get "update_avaluo" => "avaluos#update_avaluo", :as => "update_avaluo"

  get 'avaluos/update_description_val', :as => 'update_description_val'
  get 'avaluos/update_state_val', :as => 'update_state_val'
  get 'avaluos/update_tabla_total', :as => 'update_tabla_total'
  post "aval_update" => "avaluos#update", :as => "aval_update"

  get "index_images" => "images#index", :as => "index_images"
  post "destroy_image" => "images#destroy", :as => "destroy_image"

  get "index_meeting" => "meetings#index", :as => "index_meeting"
  get "new_meeting" => "meetings#new", :as => "new_meeting"
  get "edit_meeting" => "meetings#edit", :as => "edit_meeting"
  post "destroy_meeting" => "meetings#destroy", :as => "destroy_meeting"

  get "index_diary" => "diaries#index", :as => "index_diary"
  get "new_diary" => "diaries#new", :as => "new_diary"
  get "edit_diary" => "diaries#edit", :as => "edit_diary"
  post "destroy_diary" => "diaries#destroy", :as => "destroy_diary"

  get "index_honorary" => "honoraries#index", :as => "index_honorary"
  get "new_honorary" => "honoraries#new", :as => "new_honorary"
  get "edit_honorary" => "honoraries#edit", :as => "edit_honorary"
  get "show_honorary" => "honoraries#show", :as => "show_honorary"
  get "todos_honorary" => "honoraries#todos", :as => "todos_honorary"
  post "destroy_honorary" => "honoraries#destroy", :as => "destroy_honorary"
  post "reporte_honorary" => "honoraries#reporte_honorary", :as => "reporte_honorary"

  get "index_amount" => "amounts#index", :as => "index_amount"
  get "new_amount" => "amounts#new", :as => "new_amount"
  get "edit_amount" => "amounts#edit", :as => "edit_amount"
  get "show_amount" => "amounts#show", :as => "show_amount"
  post "destroy_amount" => "amounts#destroy", :as => "destroy_amount"

  get "list_detalle" => "personas_roles_usuarios#nombres", :as => "list_detalle"

    
  resources :users
  resources :sessions
  resources :personas
  resources :roles
  resources :principal
  resources :properties
  resources :operations
  resources :channels
  resources :provinces
  resources :personas_roles_usuarios
  resources :cantons
  resources :parishes
  resources :pieces
  resources :prices
  resources :parameters
  resources :descriptions
  resources :parameters_descriptions
  resources :rebates
  resources :states
  resources :constructions
  resources :avaluos
  resources :constructions_prices
  resources :areas
  resources :images
  resources :meetings
  resources :diaries
  resources :honoraries
  resources :amounts
  resources :password_resets
  
  
match ':controller(/:action(/:id))(.:format)'

app/models/rebate.rb
class Rebate < ActiveRecord::Base
  attr_accessible :met_nombre, :met_nivel
  has_many :states, :dependent => :destroy

  validate :blanco
  def blanco
    self.met_nombre = self.met_nombre.gsub(/\s+/, " ").strip
#    self.param_val_unit = self.param_val_unit.gsub(/\s+/, " ").strip
  end
end

app/controllers/rebates_controller.rb
class RebatesController < ApplicationController
  def index
    rol_administrador = Role.find_by_rol_nombre("Administrador")
    administrador = User.joins(:roles).where(:personas_roles_users=>{:role_id=>rol_administrador.id, :user_id=>current_user})
    if current_user and administrador.exists?
      @depreciaciones = Rebate.find(:all)
      @depreciacion = Rebate.new
      respond_to do |format|
        format.js
        format.html
      end
    else
      redirect_to denegado_path
    end
  end

  def new
    @depreciacion = Rebate.new
  end

  def create
    @depreciacion = Rebate.new(params[:rebate])
    respond_to do |format|
      @depreciacion.met_nombre = @depreciacion.met_nombre.gsub(/\s+/, " ").strip
      if @depreciacion.met_nombre == ""
        @bandera = "blank"
        format.js { render "create.js"}
      else
        if Rebate.find_by_met_nombre(@depreciacion.met_nombre)
          @bandera = "exist"
          format.js { render "create.js"}
        else
          mayuscula = (@depreciacion.met_nombre).upcase
          todos_depreciaciones = Rebate.all
          todos_depreciaciones.each do |p|
            if (p.met_nombre).upcase == mayuscula
              @bandera = "exist"
            end
          end
          if @bandera == "exist"
            format.js { render "create.js"}
          else
            if @depreciacion.save
              format.html { redirect_to index_rebate_path, :notice => "Registrado"}
            end
          end
        end
      end
    end
  end

  def show
    @depreciacion = Rebate.find(params[:id])
  end

  def eliminar
    @depreciacion = Rebate.find(params[:id])
    respond_to do |format|
      if Construction.joins(:states).where(:states=>{:rebate_id=>@depreciacion.id}).exists?
        format.js { render "no_eliminar.js"}
      else
        format.js { render "eliminar.js"}
      end
    end
    rescue ActiveRecord::RecordNotFound
      redirect_to denegado_path
    return
  end

  def destroy
    @depreciacion = Rebate.find(params[:id])

    #LOCALIZAR TODOS LOS ESTADOS DEL METODO DE DEPRECIACION A ELIMINAR
    estados = State.joins(:rebate).where(:rebates=>{:id=>@depreciacion.id})
    inmuebles = Construction.find(:all, :conditions => "inm_estado != 'I'")
    inm_avaluo_update = Construction.joins(:constructions_states).where(:constructions_states=>{:construction_id => inmuebles, :state_id => estados}).select("distinct constructions_states.construction_id")
    inm_avaluo_update = Construction.where(:id => inm_avaluo_update)

    #GUARDAMOS EN UN ARREGLO LOS IDS DE LOS INMUEBLES
    ids_inm = []
    cont = 0
    inm_avaluo_update.each do |iau|
      ids_inm[cont] = iau.id
      cont+=1
    end

    #ELIMINAMOS LOS REGISTROS QUE CORRESPONDEN A LA TABLA DETALLE
    detalle_state = ConstructionsState.where(:state_id => estados)
    detalle_state.each do |ds|
      ds.destroy
    end

    #VOLVEMOS A BUSCAR LOS INMUEBLES CON LOS IDS DEL ARREGLO
    inm_avaluo_update = Construction.where(:id => ids_inm)
    inmuebles_count = inm_avaluo_update.count()

    #ACTUALIZAMOS EL AVALUO DE LOS INMUEBLES
    Construction.actualizar_avaluo_inm(inmuebles_count, inm_avaluo_update)
    @depreciacion.destroy
    redirect_to index_rebate_path
  end

  def edit
    @depreciacion = Rebate.find(params[:id])
    respond_to do |format|
      format.js { render "edit.js"}
    end
    rescue ActiveRecord::RecordNotFound
      redirect_to denegado_path
    return
  end

  def update
    @depreciacion = Rebate.new(params[:rebate])
    respond_to do |format|
      @depreciacion.met_nombre = @depreciacion.met_nombre.gsub(/\s+/, " ").strip
      if @depreciacion.met_nombre == ""
        @bandera = "blank"
        format.js { render "update.js"}
      else
        aux_depreciacion = Rebate.find(params[:id])
        if Rebate.find_by_met_nombre(@depreciacion.met_nombre) and (@depreciacion.met_nombre != aux_depreciacion.met_nombre)
          @bandera = "exist"
          format.js { render "update.js"}
        else
          mayuscula = (@depreciacion.met_nombre).upcase
          todos_depreciaciones = Rebate.all
          todos_depreciaciones.each do |p|
            if ((p.met_nombre).upcase == mayuscula) and (p.met_nombre).upcase != (aux_depreciacion.met_nombre).upcase
              @bandera = "exist"
            end
          end
          if @bandera == "exist"
            format.js { render "update.js"}
          else
            @depreciacion = Rebate.find(params[:id])
            if @depreciacion.update_attributes(params[:rebate])
              format.html { redirect_to index_rebate_path, :notice => "Registro Actualizado con Exito"}
            end
          end
        end
      end
    end
  end
end

app/helpers/rebates_helper.rb
module RebatesHelper
end

app/views/rebates/_edit.html.erb
<script>
  $("#advertencia_edit").hide();
</script>
<div id="formulario">
  <div id="form_edit_rebate">
    <%= form_for @depreciacion, :remote=>true  do |d|%>
      <table>
        <tr>
          <td><%= label_tag nil, "Metodo de Depreciacion:" %></td>
          <td><%= d.text_field :met_nombre, :id=>"rebates_edit_met_nombre", :autofocus => true %></td>
        </tr>
        <tr>
          <td colspan="2" class="centrar_obj"><%= label_tag nil, "", :id=>"advertencia_edit", :class=>"mensaje" %></td>
        </tr>
      </table>
    <%end%>
  </div>
</div>

app/views/rebates/_eliminar.html.erb
<div id="formulario">
  <div id="form_eliminar_rebate">
  <%= form_tag destroy_rebate_path do%>
    <%= label_tag nil, "Esta seguro que desea eliminar '#{@depreciacion.met_nombre}'"%>
    <%= hidden_field_tag :id, @depreciacion.id  %>
  <%end%>
  </div>
</div>

app/views/rebates/_no_eliminar.html.erb
<div id="formulario">
  <%= label_tag nil, "No puede eliminar la Depreciación '#{@depreciacion.met_nombre}' porque tiene datos asociados."%>
</div>

app/views/rebates/_show.html.erb
<div id="formulario">
  <%= label_tag nil, "", :id=>"advertencia_new", :class=>"mensaje"%>
</div>

app/views/rebates/create.js.erb
$('#rebate_new').html('<%= escape_javascript(render :partial =>'rebates/show')%>');
if ('<%= @bandera%>' == "blank")
{ $('#advertencia_new').html('<%= escape_javascript('ATENCION: Faltan datos por ingresar')%>');}
else
{ if ('<%= @bandera%>' == "exist")
  { $('#advertencia_new').html('<%= escape_javascript("#{@depreciacion.met_nombre}"+' ya existe, por favor ingrese otro nombre')%>');}
}
document.getElementById("advertencia_new").style.color="#F50E0E";
$('#rebate_new').dialog({
  resizable: false,
  height: 'auto',
  width: 'auto',
  title: "Nuevo",
  modal: true,
  buttons: {
                "OK" : function()
                {
                    $("#rebate_new").dialog("close");
                    document.getElementById("rebates_index_met_nombre").focus();
                    $('#rebates_index_met_nombre').val("");
                }
            }
});

app/views/rebates/edit.js.erb
$('#rebate_edit').html('<%= escape_javascript(render :partial =>'rebates/edit')%>');
$('#rebate_edit').dialog({
  resizable: false,
  height: 'auto',
  width: 'auto',
  title: "Editar",
  modal: true,
  buttons: {
                "Guardar": function()
                {
                    $("#form_edit_rebate form").submit();
                },
                "Cancelar" : function()
                {
                    $("#rebate_edit").dialog("close");
                }
            }
});

app/views/rebates/eliminar.js.erb
$('#rebate_delete').html('<%= escape_javascript(render :partial =>'rebates/eliminar')%>');
$('#rebate_delete').dialog({
  resizable: false,
  height: 'auto',
  width: 'auto',
  title: "Eliminar",
  modal: true,
  buttons: {
                "Aceptar": function()
                {
                    $("#form_eliminar_rebate form").submit();
                },
                "Cancelar" : function()
                {
                    $("#rebate_delete").dialog("close");
                }
            }
});

app/views/rebates/index.html.erb
<script language="JavaScript" type="text/javascript" src="/javascripts/jquery-ui.js"></script>
<link rel="stylesheet" href="/stylesheets/jquery-ui.css"></link>
<%= stylesheet_link_tag "tablas.css", :media => "screen" %>
<div id="tabla">
  <table class="bordered">
    <th><div class="titulos"><p>Metodo de Depreciacion</p></div></th>
    <th><div class="titulos"><p>Acciones</p></div></th>
    <% @depreciaciones.each do |d| %>
      <tr>
        <td><%= label_tag nil, (link_to '+', index_state_path(:rebate_id => d.id))%><%= label_tag nil, d.met_nombre %></td>
        <%#= d.met_nivel %>
        <td><%= label_tag nil, (link_to (image_tag "contenido/edit16.png"), {:action => "edit", :id => d.id}, :remote=>true) %><%= label_tag nil, (link_to (image_tag "contenido/delete16.png"), {:action => "eliminar", :id => d.id}, :remote=>true) %></td>
      </tr>
    <% end %>
    <%= form_for @depreciacion, :remote=>true do |d|%>
      <tr>
        <td><%= d.text_field :met_nombre, :id=>"rebates_index_met_nombre", :autofocus => true %></td>
        <td><%= label_tag nil, image_submit_tag("contenido/add2-16.png")%></td>
      </tr>
    <%end%>
  </table>
</div>
<div id="rebate_new">

</div>
<div id="rebate_edit">

</div>
<div id="rebate_delete">

</div>
<div id="rebate_no_delete">

</div>
<%#= link_to 'Agregar nuevo metodo de depreciacion', new_rebate_path %>

app/views/rebates/index.js.erb
window.location = '<%= index_rebate_path %>';

app/views/rebates/new.html.erb
<%= form_for @depreciacion do |d|%>
  <p>
    <%= d.label :"Metodo de Depreciacion" %>
    <%= d.text_field :met_nombre %>
  </p>
  <p>
    <%= d.label :"Nivel del metodo" %>
    <%= d.text_field :met_nivel %>
  </p>
  <p>
    <%= d.submit "Guardar"%>
  </p>
<%end%>

app/views/rebates/no_eliminar.js.erb
$('#rebate_no_delete').html('<%= escape_javascript(render :partial =>'rebates/no_eliminar')%>');
$('#rebate_no_delete').dialog({
  resizable: false,
  height: 'auto',
  width: 'auto',
  title: "Eliminar",
  modal: true,
  buttons: {
                "Aceptar": function()
                {
                    $("#rebate_no_delete").dialog("close");
                }
            }
});

app/views/rebates/update.js.erb
if ('<%= @bandera%>' == "blank")
{ $('#advertencia_edit').html('<%= escape_javascript('ATENCION: Faltan datos por ingresar')%>');}
else
{ if ('<%= @bandera%>' == "exist")
  { $('#advertencia_edit').html('<%= escape_javascript('El nombre ya existe, por favor ingrese uno diferente')%>');}
}
document.getElementById("advertencia_edit").style.color="#F50E0E";
$('#advertencia_edit').show();
setTimeout(function(){$('#advertencia_edit').hide()},6000);
document.getElementById("rebates_edit_met_nombre").focus();
$("#rebates_edit_met_nombre").val("");